---
title: "DESI thyroid Preprocessing"
author: "Jacob Mardick"
date: "`r format(Sys.time(), '%B %d, %Y %H:%M')`"
knit: (function(inputFile, encoding) { 
      proj_name <- tools::file_path_sans_ext(basename(inputFile));
      out_dir <- file.path("outputs", paste0(proj_name, "_", Sys.Date()));
      if(!file.exists(out_dir)) {   dir.create(out_dir) };
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                        out_dir, 
                        paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_", proj_name, ".html"))) 
                        })

output: 
  html_document:
    keep_md: yes
    df_print: paged
    toc: false
geometry: margin=0.5in
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
.main-container {
max-width: 1600px;
margin-left: auto;
margin-right: auto;
}
</style>
```

```{css, echo=FALSE}
h1, h2, h3, h4, h5 {
font-size: 20px;
}

h1, h2, h3, h4, h5, p {
text-align: center;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, cache = FALSE)
```

```{r libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(reshape2)
library(readxl)
library(sqldf)

library(stringr)
library(doParallel)
library(fcluster)
library(johnfuncs)
```

```{r user input}
## Full path to folder with sample files (excel or csv, or raw Thermo files)
## PASTE PATH IN BETWEEN INNER PARENTHASIS WITH QUOTES ON THE OUTSIDE -- NO NEED TO CHANGE BACKSLASHES TO FORWARD SLASHES
thyroid_sample_dir <- gsub("\\\\", "/", r"(C:\Users\Jacob\Documents\DESI Thyroid (UT QE - Rachel)\files)")

## Full path to background peak list, otherwise NULL
background_file <- NULL
```

```{r create directory for output files, include = FALSE}
proj_name <- tools::file_path_sans_ext(basename(rstudioapi::getSourceEditorContext()$path))

out_dir <- file.path("outputs", paste0(proj_name, "_", Sys.Date()))

if(!file.exists(out_dir)) {   
  dir.create(out_dir, recursive = TRUE) 
  }

files_dir <- file.path(out_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", proj_name, "_files"))

if(!file.exists(files_dir)) {   
  dir.create(files_dir, recursive = TRUE) 
  }
```

## **Data Processing**

### **Read in Files**

```{r classes}
## read sub-directories for class names
classes <- gsub(file.path(thyroid_sample_dir, "/"), "", list.dirs(thyroid_sample_dir, recursive=FALSE), fixed=TRUE)
## Remove FNA class for now
classes <- classes[!classes %in% c("FNA Extracted Files", "FNA Image Predictions")]
```

```{r file and sample names}
## List file names
file_name_list <- lapply(classes, function(class_dir) {
  files <- list.files(path = file.path(thyroid_sample_dir, class_dir), 
                      pattern = "\\.csv$|\\.xlsx?$", 
                      full.names = TRUE)
  sort(files)
})

## Assign names to each list entry
names(file_name_list) <- classes

## List sample names
sample_names_list <- lapply(file_name_list, function(files) {
  tools::file_path_sans_ext(basename(files))
})

names(sample_names_list) <- classes

## Vector of sample names
sample_names <- unlist(sample_names_list)
```

```{r dataList}
## Read DESI-MSI pixel spectra (output of msipost in MatLab?)
dataList <- lapply(file_name_list, function(x) read_files(x))

dataList <- lapply(seq_along(dataList), \(i) setNames(dataList[[i]], sample_names_list[[i]]))
names(dataList) <- classes

save(dataList, file = file.path(files_dir, "02_dataList.RData"))
```

```{r pixelInfoList}
## Read DESI-MSI pixel info
pixelInfoList <- mapply(function(x,y) read_headers(x,y), x=file_name_list, y=classes, SIMPLIFY = FALSE)

## calculate TIC for each pixel
pixelInfoList <- mapply(function(x,y) 
  mapply(function(x2,y2) calculateCTIC(x2,y2), x2=x, y2=y, SIMPLIFY = FALSE), 
  x=pixelInfoList, y=dataList, SIMPLIFY = FALSE)

pixelInfoList <- lapply(seq_along(pixelInfoList), \(i) setNames(pixelInfoList[[i]],sample_names_list[[i]]))
names(pixelInfoList) <- classes

## Assign Patient Number to Pixels
pixelInfoAll <- assignPatNum(pixelInfoList)

## Tibble of pixel info
pi <- pixelInfoTibble(pixelInfoAll)

# create a new column `x` with the three columns collapsed together
pi$pixel_name <- paste0(pi$name, ".", pi$scanNum)

save(pi, pixelInfoList, pixelInfoAll, file = file.path(files_dir, "01_pixel_information.RData"))
```

## **Session Info**

```{r Session Info}
sessionInfo()
```
