---
title: "DESI Kidney Preprocessing"
author: "Jacob Mardick"
date: "`r format(Sys.time(), '%B %d, %Y %H:%M')`"
knit: (function(inputFile, encoding) { 
      proj_name <- tools::file_path_sans_ext(basename(inputFile));
      out_dir <- file.path("outputs", paste0(proj_name, "_", Sys.Date()));
      if(!file.exists(out_dir)) {   dir.create(out_dir) };
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), 
                        out_dir, 
                        paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"),"_", proj_name, ".html"))) 
                        })

output: 
  html_document:
    keep_md: yes
    df_print: paged
    toc: false
geometry: margin=0.5in
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style type="text/css">
.main-container {
max-width: 1600px;
margin-left: auto;
margin-right: auto;
}
</style>
```

```{css, echo=FALSE}
h1, h2, h3, h4, h5 {
font-size: 20px;
}

h1, h2, h3, h4, h5, p {
text-align: center;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, cache = FALSE)
```

```{r libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(reshape2)
library(readxl)
library(sqldf)

library(stringr)
library(doParallel)
library(fcluster)
library(johnfuncs)
```

```{r user input}
## Full path to folder with sample files (excel or csv, or raw Thermo files)
## PASTE PATH IN BETWEEN INNER PARENTHASIS WITH QUOTES ON THE OUTSIDE -- NO NEED TO CHANGE BACKSLASHES TO FORWARD SLASHES
kidney_sample_dir <- gsub("\\\\", "/", r"(C:\Users\Jacob\Box\Eberlin_Lab_BCM\People\Past group members\Jialing\Documents\KidneyDatawithOriginalName\data)")

## Full path to background peak list, otherwise NULL
background_file <- NULL

## ---------------------------------------------------------------------------

## Mass range to filter
mass_range <- c(100,1000)

## Peak Alignment Method: "clustering" or "binning" (TBD on "featurelist")
peak_alignment_method <- "clustering"

## If peak alignment method is "clustering":
## Height at which to cut dendrogram to determine clusters
clust_h <- 0.05

## Method to handle many intensities in one cluster centroid: 
## sum the intensities of peaks in one cluster centroid ("sumints", default) 
## or use the max intensity ("maxint")
clust_int_method  <-  "sumints"

## Normalization Method: "tic", "maxpeak", "median", "medianlog", or "none"
normalization_method <- "tic" 
```

```{r create directory for output files, include = FALSE}
proj_name <- tools::file_path_sans_ext(basename(rstudioapi::getSourceEditorContext()$path))

out_dir <- file.path("outputs", paste0(proj_name, "_", Sys.Date()))

if(!file.exists(out_dir)) {   
  dir.create(out_dir, recursive = TRUE) 
  }

files_dir <- file.path(out_dir, paste0(format(Sys.time(), "%Y-%m-%d_%H.%M"), "_", proj_name, "_files"))

if(!file.exists(files_dir)) {   
  dir.create(files_dir, recursive = TRUE) 
  }
```

## **Data Processing**

### **Read in Files**

```{r classes}
## read sub-directories for class names
classes <- gsub(file.path(kidney_sample_dir, "/"), "", list.dirs(kidney_sample_dir, recursive=FALSE), fixed=TRUE)
```

```{r file and sample names}
## List file names
file_name_list <- lapply(classes, function(class_dir) {
  files <- list.files(path = file.path(kidney_sample_dir, class_dir), 
                      pattern = "\\.csv$|\\.xlsx?$", 
                      full.names = TRUE)
  sort(files)
})

## Assign names to each list entry
names(file_name_list) <- classes

## List sample names
sample_names_list <- lapply(file_name_list, function(files) {
  tools::file_path_sans_ext(basename(files))
})

names(sample_names_list) <- classes

## Vector of sample names
sample_names <- unlist(sample_names_list)
```

```{r dataList}
## Read DESI-MSI pixel spectra (output of msipost in MatLab?)
dataList <- lapply(file_name_list, function(x) read_files(x))

dataList <- lapply(seq_along(dataList), \(i) setNames(dataList[[i]], sample_names_list[[i]]))
names(dataList) <- classes

save(dataList, file = file.path(files_dir, "02_dataList.RData"))
```

```{r pixelInfoList}
## Read DESI-MSI pixel info
pixelInfoList <- mapply(function(x,y) read_headers(x,y), x=file_name_list, y=classes, SIMPLIFY = FALSE)

## calculate TIC for each pixel
pixelInfoList <- mapply(function(x,y) 
  mapply(function(x2,y2) calculateCTIC(x2,y2), x2=x, y2=y, SIMPLIFY = FALSE), 
  x=pixelInfoList, y=dataList, SIMPLIFY = FALSE)

pixelInfoList <- lapply(seq_along(pixelInfoList), \(i) setNames(pixelInfoList[[i]],sample_names_list[[i]]))
names(pixelInfoList) <- classes

## Assign Patient Number to Pixels
pixelInfoAll <- assignPatNum(pixelInfoList)

## Tibble of pixel info
pi <- pixelInfoTibble(pixelInfoAll)

# create a new column `x` with the three columns collapsed together
pi$pixel_name <- paste0(pi$name, ".", pi$scanNum)

save(pi, pixelInfoList, pixelInfoAll, file = file.path(files_dir, "01_pixel_information.RData"))
```

### **Peak Alignment**

#### Peak Alignment: One-Dimensional Heirarchical Clustering

```{r Clustering Peak Alignment}
## If peak alignment method is clustering
if (peak_alignment_method == "clustering") {
  
  ## List of all m/z in each class
  #classMZList <- lapply(dataList, function(x) round(sort(extract_peaks(x)), 3))
  ## round mass to 3 decimal places b/c mass accuracy of instrument is ~ 1 ppm?
  
  ## If background peak list: add background peaks to clustering
  if (!is.null(background_file)) {
    bg_mz <- unlist(read.csv(background_file, header = FALSE))
    
    sample_mz <-sort(unlist(lapply(dataList, function(x) round(sort(extract_peaks(x)), 3))))
    
    all_mz <- sort(c(bg_mz, sample_mz))
    
  } else { ## If no background peak list
    all_mz <- sort(unlist(lapply(dataList, function(x) round(sort(extract_peaks(x)), 3))))
  }
  
  ## Cluster peaks into centroids
  tree <- fcluster(all_mz)
  clust_mz <- fcutree(all_mz, tree, h=clust_h)
  clustMZ <- sort(clust_mz$cen)
  
  ## Match cluster centroids to sample peaks
  clusterMatrixList <- lapply(dataList, function(x, y, z, w) 
    get_cluster_matrix(x, y, z, w), y=clustMZ, z = clust_h, w = clust_int_method)
  
  preprocList <- lapply(clusterMatrixList, function(x) get_data_matrix_clustering(x))
  
  save(preprocList, file = file.path(files_dir, 
                                 paste0("03_", peak_alignment_method,
                                        "_h", clust_h, clust_int_method,
                                        "_preprocList.RData")))
  
  aligned_spectra <- do.call(rbind, preprocList)
  
  colnames(aligned_spectra) <- clustMZ
  rownames(aligned_spectra) <- pi$pixel_name
  
  ## FILTER #1: REMOVE RARE/UNCOMMON PEAKS PRESENT < 10% SAMPLES
  mz_count_filter <- Matrix::colSums(aligned_spectra != 0) > as.integer(nrow(aligned_spectra)*0.10)
  aligned_spectra <- aligned_spectra[, mz_count_filter]

  ## FILTER #2: REMOVE BACKGROUND PEAKS (IF BACKGROUND FILE PRESENT)
  if (!is.null(background_file)) {
    ## match bg_mz to cluster centroid
    temp_a <- data.frame(cluster_id = clust_mz$cluster_index,
                         all_mz = all_mz)
    
    temp_b <- data.frame(clust_centroid = clust_mz$centroid, 
                         cluster_id = unique(clust_mz$cluster_index)[order(unique(clust_mz$cluster_index))])
    
    temp_c <- merge(temp_a, temp_b, by = "cluster_id")
    
    bg_centroids <- unique(temp_c[temp_c$all_mz %in% bg_mz, ])
    
    ## Remove peaks from aligned_spectra that are in bg_mz_centroid
    aligned_spectra <- aligned_spectra[, !(colnames(aligned_spectra) %in% bg_centroids$clust_centroid)]
  }
  filtered_mz <- as.numeric(colnames(aligned_spectra))
  
  # FILTER #3: RETAIN PEAKS WITHIN MASS RANGE
  mz_range_filter <-  filtered_mz > mass_range[1] & filtered_mz < mass_range[2]
  aligned_spectra <- aligned_spectra[, mz_range_filter]
  
  filtered_mz <- as.numeric(colnames(aligned_spectra))
  
  save(aligned_spectra, filtered_mz, file = file.path(files_dir, paste0("04_aligned_spectra.RData")))
}
```

#### Peak Alignment: Binning

```{r peak alignment binning}
if (peak_alignment_method == "binning") {
  ## Hard coded that m/z values are rounded to 2 decimal places and intensities of peaks that fall into the same bin are summed (by John Lin). 
  ## TBD about changing this - FEJ 2024-09-06
  
  #classMZList <- lapply(dataList, function(x) round(sort(extract_peaks(x)), 2))
  
  all_mz <- sort(unlist(lapply(dataList, function(x) round(sort(extract_peaks(x)), 2))))
  
  names(all_mz) <- all_mz
  
  ## FILTER #1: REMOVE RARE/UNCOMMON PEAKS PRESENT < 10% SAMPLES
  mz_count <- table(all_mz)
  mz_count_filter <- mz_count > as.integer(length(unlist(pixelInfoList))*0.10)
  filtered_mz <- as.numeric(names(mz_count)[mz_count_filter])
  
  ## Bin sample peaks
  preprocList <- lapply(dataList, function(x,z) get_data_matrix_binning(x,z), z=filtered_mz)
  
  save(preprocList, file = file.path(files_dir, 
                                 paste0("03_", peak_alignment_method,"_preprocList.RData")))
  
  aligned_spectra <- do.call(rbind, preprocList)
  
  colnames(aligned_spectra) <- filtered_mz
  rownames(aligned_spectra) <- pi$pixel_name
  
  ## FILTER #2: REMOVE BACKGROUND PEAKS (IF BACKGROUND FILE PRESENT)
  if (!is.null(background_file)) {
    bg_mz <- round(unlist(read.csv(background_file, header = FALSE)),2) ## round to 2 decimal places for binned values
    aligned_spectra <- aligned_spectra[, !(colnames(aligned_spectra) %in% bg_mz)]
    filtered_mz <- as.numeric(colnames(aligned_spectra))
  }
  
  # FILTER #3: MASS RANGE
  mz_range_filter <-  filtered_mz > mass_range[1] & filtered_mz < mass_range[2]
  aligned_spectra <- aligned_spectra[, mz_range_filter]
  
  filtered_mz <- as.numeric(colnames(aligned_spectra))
  
  save(aligned_spectra, filtered_mz, file = file.path(files_dir, paste0("04_aligned_spectra.RData")))
}
```

### **Create yall object**

```{r yall}
## create yall object for each pixel
yall <- foreach(i = 1:length(preprocList), .combine = c) %do% {
  rep(i, nrow(preprocList[[i]]))
}

## factorize yall
yall <- factor(yall, labels = classes)
```

```{r}
save(mass_range, peak_alignment_method, clust_h, normalization_method,
     classes, file_name_list, sample_names, pixelInfoList, pixelInfoAll, pi, filtered_mz, yall, 
     file = file.path(files_dir, paste0("00_", proj_name, "_Robjects_for_analysis.RData")))
```

## **Session Info**

```{r Session Info}
sessionInfo()
```
